# Generated by Django 2.1.1 on 2018-09-06 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_auto_20180906_1610'),
    ]

    operations = [
        migrations.CreateModel(
            name='Print1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField(max_length=200)),
            ],
        ),
    ]
