# Generated by Django 2.1.1 on 2018-09-06 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_print1'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='print1',
            field=models.CharField(default='some string', max_length=120),
        ),
    ]
