# Generated by Django 2.1.1 on 2018-09-06 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_auto_20180906_1653'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='print1',
            field=models.CharField(default='', max_length=120),
        ),
        migrations.AlterField(
            model_name='post',
            name='print2',
            field=models.CharField(default='', max_length=120),
        ),
        migrations.AlterField(
            model_name='post',
            name='print3',
            field=models.CharField(default='', max_length=120),
        ),
        migrations.AlterField(
            model_name='post',
            name='print4',
            field=models.CharField(default='', max_length=120),
        ),
        migrations.AlterField(
            model_name='post',
            name='print5',
            field=models.CharField(default='', max_length=120),
        ),
    ]
