# Generated by Django 2.1.1 on 2018-09-06 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_auto_20180906_1656'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=25)),
                ('age', models.IntegerField()),
                ('department', models.CharField(max_length=3)),
                ('wage', models.FloatField()),
            ],
        ),
        migrations.DeleteModel(
            name='Print1',
        ),
    ]
