# Generated by Django 2.1.1 on 2018-09-06 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0010_auto_20180906_1710'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='id_of_people',
            field=models.CharField(default='', max_length=120),
        ),
    ]
